name: QA_Validation_Process

on:
  pull_request:
    branches: [ main ] 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Execute Microservices Tests
       
        run: npm run test 

      - name: Final Check
        if: success()
        run: echo "✅ Los tests pasaron con éxito. Ingeniero, el código está listo para su revisión."